In [2]:
import torch

H = 3
W = 3
padding = 1
stride = 2

kernel_h = 3
kernel_w = 3

In [3]:
out_h = (H + 2 * padding - kernel_h) // stride + 1
out_w = (W + 2 * padding - kernel_w) // stride + 1
print(out_h, out_w)

2 2


In [8]:
offset_h = torch.arange(kernel_h).reshape(-1, 1).repeat(1, kernel_w).reshape(-1)
print(offset_h)

start_h = torch.arange(out_h) * stride
start_h = start_h.reshape(-1, 1).repeat(1, out_w).reshape(-1)
print(start_h)

tensor([0, 0, 0, 1, 1, 1, 2, 2, 2])
tensor([0, 0, 2, 2])


In [ ]:
offset_h = offset_h.reshape(-1,1)
print(offset_h)

tensor([[0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2]])


In [11]:
start_h = start_h.reshape(1, -1)
print(start_h)

tensor([[0, 0, 2, 2]])


In [12]:
h_idx = offset_h + start_h
print(h_idx)

tensor([[0, 0, 2, 2],
        [0, 0, 2, 2],
        [0, 0, 2, 2],
        [1, 1, 3, 3],
        [1, 1, 3, 3],
        [1, 1, 3, 3],
        [2, 2, 4, 4],
        [2, 2, 4, 4],
        [2, 2, 4, 4]])
